shell fish

# Cursor settings
cursor_shape beam
cursor_blink_interval 0
cursor_stop_blinking_after 0
cursor_trail 25
cursor_trail_color #00ffff

enable_wayland yes

# Transparencia nativa
background_opacity 0.5

# Opcional: un ligero blur interno
#background_blur 10

# === Light theme - Catppuccin Latte inspired ===
#foreground            #4c4f69
#background            #eff1f5
#selection_foreground  #ffffff
#selection_background  #7287fd

color0  #D8DEE9
color8  #E5E9F0
color1  #BF616A
color9  #D06F79
color2  #A3BE8C
color10 #B1D196
color3  #EBCB8B
color11 #F0D399
color4  #5E81AC
color12 #81A1C1
color5  #B48EAD
color13 #C895BF
color6  #88C0D0
color14 #8FBCBB
color7  #4C566A
color15 #2E3440
