--
--   _  _               _              _         ___ _                    _
--  | || |_  _ _ __ _ _| |__ _ _ _  __| |  ___  | __| |_ __  ___ _ _   _ | |_ _
--  | __ | || | '_ \ '_| / _` | ' \/ _` | |___| | _|| | '  \/ -_) '_| | || | '_|
--  |_||_|\_, | .__/_| |_\__,_|_||_\__,_|       |___|_|_|_|_\___|_|    \__/|_|
--        |__/|_|
--          ___           __ _
--   ___   / __|___ _ _  / _(_)__ _
--  |___| | (__/ _ \ ' \|  _| / _` |
--         \___\___/_||_|_| |_\__, |
--                            |___/
--

-- ╭───────────────────────────────────────────────────╮
-- │  MONITORES · resolución, posición y escala        │
-- ╰───────────────────────────────────────────────────╯
--   Sintaxis: monitor = <nombre>, <resolución@refresh>, <posición_X>x<posición_Y>, <escala>

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-4",
    mode = "1920x1080@75",
    position = "0x0",
    scale = "1.00",
})

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "1920x0",
    scale = "1.00",
})

-- Monitor HP conectado directamente por HDMI a la Docking Station (desactivado)
--monitor= DP-5, 1920x1080@60, 0x0, 1.00

-- Monitor HP conectado directamente por HDMI a la PC (desactivado)
--monitor= HDMI-A-1, 1920x1080@60, 0x0, 1.00

-- ╭───────────────────────────────────────────────────╮
-- │  AUTOSTART · programas que arrancan con Hyprland  │
-- ╰───────────────────────────────────────────────────╯

-- Ícono de NetworkManager en la bandeja del sistema (waybar)

-- ╭───────────────────────────────────────────────────╮
-- │  INPUT · teclado, touchpad y mouse                │
-- ╰───────────────────────────────────────────────────╯
--   Más info: https://wiki.hyprland.org/Configuring/Variables/

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.window_rule({
    match = {
        title = "(^(kitty)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(garuda-assistant)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(garuda-boot-options)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(garuda-boot-repair)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(garuda-gamer)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(garuda-network-assistant)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(garuda-settings-manager)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(garuda-welcome)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "(^(calamares)$)",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(kitty)$",
    },
    float = false,
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("swaymsg input '*' xkb_layout us,es"))

hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + code:36", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("nwgbar"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + SHIFT + code:65", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + SUPER_L", hl.dsp.exec_cmd("pkill wofi || wofi --normal-window --show drun"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("emote"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("nwg-drawer -mb 10 -mr 10 -ml 10 -mt 10"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.layout("togglesplit"))

hl.bind(mainMod .. " + F1", hl.dsp.exec_cmd("firedragon"))
hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd("thunderbird"))
hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + F4", hl.dsp.exec_cmd("geany"))
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd("github-desktop"))
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd("gparted"))
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd("inkscape"))
hl.bind(mainMod .. " + F8", hl.dsp.exec_cmd("blender"))
hl.bind(mainMod .. " + F9", hl.dsp.exec_cmd("meld"))
hl.bind(mainMod .. " + F10", hl.dsp.exec_cmd("joplin-desktop"))
hl.bind(mainMod .. " + F11", hl.dsp.exec_cmd("snapper-tools"))
hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd("galculator"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("ALT + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("ALT + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("ALT + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("ALT + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("ALT + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("ALT + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("ALT + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("ALT + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind("ALT + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind("ALT + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + TAB", hl.dsp.window.cycle_next({ next = true }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- TODO: manual review — top-level key 'layerrulev2 = blur , waybar' has no enclosing section
-- TODO: manual review — top-level key 'layerrulev2 = ignorezero , waybar' has no enclosing section

hl.bind("code:122", hl.dsp.exec_cmd("pamixer --decrease 5; notify-send \" Volume: \"$(pamixer --get-volume) -t 500"))
hl.bind("code:123", hl.dsp.exec_cmd("pamixer --increase 5; notify-send \" Volume: \"$(pamixer --get-volume) -t 500"))
hl.bind("code:121", hl.dsp.exec_cmd("pamixer --toggle-mute; notify-send \" Volume: Toggle-mute\" -t 500"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle; notify-send \"System Mic: Toggle-mute\" -t 500"))

hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }))
hl.bind("code:232", hl.dsp.exec_cmd("brightnessctl -c backlight set 5%-"))
hl.bind("code:233", hl.dsp.exec_cmd("brightnessctl -c backlight set +5%"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("killall -9 wpaperd && wpaperd"))

hl.bind("Print", hl.dsp.exec_cmd("grimblast --notify copysave area ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S)_selection.png"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("grimblast --notify copysave active ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S)_window.png"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grimblast --notify copysave screen ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S)_display.png"))

hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    hl.bind("right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
    hl.bind("L", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
    hl.bind("H", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
    hl.bind("K", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
    hl.bind("J", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "+0" }))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.workspace.toggle_special("magic"))

-- TODO: manual review — top-level key 'blurls = wofi' has no enclosing section
-- TODO: manual review — top-level key 'blurls = thunar' has no enclosing section
-- TODO: manual review — top-level key 'blurls = gedit' has no enclosing section
-- TODO: manual review — top-level key 'blurls = gtk-layer-shell' has no enclosing section
-- TODO: manual review — top-level key 'blurls = catfish' has no enclosing section

hl.window_rule({
    match = {
        title = "(^(thunar)$)",
    },
    opacity = "0.85 override 0.85 override",
})

hl.window_rule({
    match = {
        title = "(^(gedit)$)",
    },
    opacity = "0.85 override 0.85 override",
})

hl.window_rule({
    match = {
        title = "(^(catfish)$)",
    },
    opacity = "0.85 override 0.85 override",
})

hl.window_rule({
    match = {
        title = "(^(wofi)$)",
    },
    stay_focused = true,
})

hl.window_rule({
    match = {
        float = 1,
    },
    opacity = "0.85 0.85",
})

hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))

hl.bind("code:172", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("code:171", hl.dsp.exec_cmd("playerctl next"))
hl.bind("code:173", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("kitty -e ~/.local/bin/bear/implement_gum.sh enable"))

hl.bind(mainMod .. " + I", hl.dsp.exec_cmd(".local/bin/calamares.sh"))

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
-- TODO: manual review — malformed env on line 434: KITTY_ENABLE_WAYLAND=1
-- TODO: manual review — malformed env on line 435: WLR_USE_LIBINPUT=1

hl.config({
    input = {
        kb_layout = "us,es", -- Dos layouts: inglés y español
        kb_variant = "",
        kb_model = "",
        kb_options = "grp:win_space_toggle", -- Cambiar de idioma con Win+Espacio
        kb_rules = "",
        numlock_by_default = true, -- Numlock activado al iniciar
        follow_mouse = 1, -- El foco de ventana sigue al mouse
        touchpad = {
            natural_scroll = true, -- Scroll "natural" (como en móviles)
            tap_to_click = true, -- Tocar el touchpad = clic
            disable_while_typing = true, -- Desactiva touchpad mientras escribes
        },
        sensitivity = 0, -- Sensibilidad del mouse: -1.0 a 1.0 (0 = sin cambios)
    },
    -- ╭───────────────────────────────────────────────────╮
    -- │  GENERAL · bordes, gaps y layout                  │
    -- ╰───────────────────────────────────────────────────╯
    general = {
        gaps_in = 5, -- Espacio entre ventanas
        gaps_out = 10, -- Espacio entre ventanas y bordes de pantalla
        border_size = 2, -- Grosor del borde de ventana
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(8f00ffee)" }, angle = 45 }, -- Color borde ventana activa
            inactive_border = "rgba(595959aa)", -- Color borde ventana inactiva
        },
        layout = "dwindle", -- Tipo de organización de ventanas (tiling)
    },
    -- ╭───────────────────────────────────────────────────╮
    -- │  DECORACIÓN · esquinas, blur y sombras            │
    -- ╰───────────────────────────────────────────────────╯
    decoration = {
        rounding = 10, -- Qué tan redondeadas son las esquinas de las ventanas
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
        },
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
    },
    -- ╭───────────────────────────────────────────────────╮
    -- │  ANIMACIONES · curvas y transiciones              │
    -- ╰───────────────────────────────────────────────────╯
    animations = {
        enabled = true,
    },
    -- ╭───────────────────────────────────────────────────╮
    -- │  DWINDLE · organización en mosaico                │
    -- ╰───────────────────────────────────────────────────╯
    dwindle = {
        preserve_split = true, -- Mantiene la división de pantalla al cerrar ventanas
    },
    master = {
        new_status = "master", -- Config del layout alternativo "master"
    },
    misc = {
        disable_hyprland_logo = true, -- Oculta el logo de Hyprland de fondo
    },
    -- ╭───────────────────────────────────────────────────╮
    -- │  REGLAS DE VENTANA · flotante, tile, opacidad     │
    -- ╰───────────────────────────────────────────────────╯
    --   Controlan cómo se comporta cada aplicación: flotante, tile, opacidad, etc.
    --   Más info: https://wiki.hyprland.org/Configuring/Window-Rules/
    -- Estas ventanas se abren SIEMPRE flotantes (no en mosaico)
    -- NOTA: estas reglas de abajo se agregaron para que Kitty (y antes NetBeans)
    -- se comporten en modo "tile" (mosaico) en vez de flotar, ya que por defecto
    -- tendían a abrirse flotando y no encajaban bien con el resto de ventanas.
    -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$   # (desactivada, ya no se usa)
    --windowrulev2 = noborder, class:^(Apache NetBeans IDE 26)$   # (desactivada)
    --windowrulev2 = float, xwayland:1, title:^(.*)$, windowtype:^(popup|dialog)$
    --windowrulev2 = noanim, xwayland:1, windowtype:^(popup|dialog)$
    -- ╭───────────────────────────────────────────────────╮
    -- │  MAINMOD · SUPER como tecla modificadora          │
    -- ╰───────────────────────────────────────────────────╯
    --   Todo atajo que empiece con "$mainMod" en realidad usa la tecla SUPER (Win)
    -- Cambiar layout de teclado con SUPER + Espacio
    -- ╭───────────────────────────────────────────────────╮
    -- │  ATAJOS PRINCIPALES · terminal, cerrar, launcher  │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  TECLAS F1-F12 · lanzar aplicaciones              │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  FOCO · mover entre ventanas · flechas o HJKL     │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  WORKSPACES · cambiar con SUPER + número          │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  MOVER A WORKSPACE · ALT + SHIFT + número         │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  MOVER SIN SEGUIR · SUPER + SHIFT + número        │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  WORKSPACES · rueda del mouse + SUPER             │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  MOUSE · mover y redimensionar arrastrando        │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  WALLPAPER · fondo de pantalla                    │
    -- ╰───────────────────────────────────────────────────╯
    --exec-once = wpaperd                                          # (desactivado)
    --exec-once = ~/.local/bin/cambiarWallpaper.sh                  # (desactivado)
    -- ╭───────────────────────────────────────────────────╮
    -- │  WAYBAR · barra de estado                         │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  VOLUMEN · teclas multimedia y micrófono          │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  OTROS ATAJOS · fullscreen, brillo, navegador     │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  CAPTURAS · screenshots con grimblast             │
    -- ╰───────────────────────────────────────────────────╯
    --bind = ,Print, exec, grim -g "$(slurp)" - | swappy -f -                        # Captura de una selección
    --bind = CTRL, Print, exec, .config/hypr/scripts/screenshot_window.sh            # Captura de una ventana
    --bind = SHIFT, Print, exec, .config/hypr/scripts/screenshot_display.sh          # Captura de toda la pantalla
    -- ╭───────────────────────────────────────────────────╮
    -- │  SUBMAP RESIZE · SUPER+R, flechas o HJKL, ESC     │
    -- ╰───────────────────────────────────────────────────╯
    --   Al presionar SUPER+R entras a este "modo resize"; usas flechas o H/J/K/L
    --   para achicar/agrandar la ventana activa, y ESC para salir del modo.
    -- ╭───────────────────────────────────────────────────╮
    -- │  MOVER VENTANA · SUPER + SHIFT + flechas/HJKL     │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  WORKSPACE MAGIC · scratchpad oculto              │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  BLUR Y OPACIDAD · ventanas y menús               │
    -- ╰───────────────────────────────────────────────────╯
    -- Opacidad para ventanas específicas
    -- Opacidad para CUALQUIER ventana flotante
    -- ╭───────────────────────────────────────────────────╮
    -- │  MÁS AUTOSTART · notificaciones y polkit          │
    -- ╰───────────────────────────────────────────────────╯
    -- pre-ejecuciones (en desarrollo/experimental)
    -- ╭───────────────────────────────────────────────────╮
    -- │  CLIPBOARD · historial con cliphist               │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  MULTIMEDIA · play, pause, siguiente, anterior    │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  GTK · temas e íconos                             │
    -- ╰───────────────────────────────────────────────────╯
    -- ╭───────────────────────────────────────────────────╮
    -- │  RENDIMIENTO · VFR y consumo de energía           │
    -- ╰───────────────────────────────────────────────────╯
    --   Más info: https://wiki.hyprland.org/Configuring/Performance/
    -- ╭───────────────────────────────────────────────────╮
    -- │  GARUDA · herramientas y scripts propios          │
    -- ╰───────────────────────────────────────────────────╯
    -- SUPER+SHIFT+G -> Habilita "G-Hyprland" (script propio del usuario)
    -- NOTA: se cambió "footclient" por "kitty" ya que el paquete foot fue desinstalado
    -- SUPER+I -> Ejecuta el instalador/asistente de Garuda Hyprland
    -- ╭───────────────────────────────────────────────────╮
    -- │  VARIABLES DE ENTORNO                             │
    -- ╰───────────────────────────────────────────────────╯
    -- Nota: preferimos configurar cosas mediante scripts -> revisar el archivo "hyprstart"
    -- ╭───────────────────────────────────────────────────╮
    -- │  ECOSISTEMA HYPR · hypridle                       │
    -- ╰───────────────────────────────────────────────────╯
})

hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 2 && ~/.local/bin/wallpaper-loop.sh")
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("exec xrdb -load ~/.Xresources")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("apply-gsettings")
    hl.exec_cmd("hypridle")
end)

